### ISSUE TITLE
Please i need your Help ASAP

### ISSUE THREAD

**Issue by mostafaelliethy** [ragundez/PyData#3]
![2016-08-31-010126_1024x768_scrot](https://cloud.githubusercontent.com/assets/21345980/18110221/fd73f0e4-6f16-11e6-8de2-2c8c9246f556.png)
![2016-08-31-010222_1024x768_scrot](https://cloud.githubusercontent.com/assets/21345980/18110222/fd870738-6f16-11e6-9339-9eb13ba94f76.png)
![2016-08-31-010305_1024x768_scrot](https://cloud.githubusercontent.com/assets/21345980/18110223/fd8ae10a-6f16-11e6-9b56-9ed2844c1427.png)

I'm Trying to use your system as a module in my graduation project with raspberry pi 2 and a Picamera, any help well be appropriated.

all requirements are satisfied, my problem is exactly with the PiCamera to get it running

Thanks and best Regards
Mostafa

**Comment by rragundez** [comment]
Hi @mostafaelliethy can you try this:

```python
import cv2
video = cv2.VideoCapture(0)
ret, frame = video.read()
print ret
print type(frame)
```

and show me the output. I think your camera is not getting the frames and returning `None`

**Comment by rragundez** [comment]
Hi @mostafaelliethy  it seems to me you are trying to mix very different functionality. I have no experience with the PiCamera package.  In line 4 you are creating a camera object `camera = PiCamera()` but the class `VideoCamera` it is also what it does as you can see in the  `__init__`
Then inside the `get_frame` method you are reading multiple frames from the `PiCamera` but then also reading with the class using `self.video.read()`.  So I am sorry but it is difficult to help you as it is not just one small thing. 
If the camera is recognize using `cv2.videoCapture(0)` then I think you don't need the PiCamera package, if it doesn't, then you need to rewrite the complete class using that package instead of cv2 so that the other parts of the application don't break.

You can try to do:

``` python
>>> import cv2
>>> video = cv2.VideoCapture(0)
>>> ret, frame = video.read()
>>> print ret
>>> print type(frame)
```

If that works and it is not returning `None` then the camera is being picked up correctly by OpenCV(cv2) and you can avoid `PiCamera()`.

**Comment by AurangzaibKhan** [comment]
Sir i want make Gui for this face recognition project i just want to use three buttons "Addperson", "Recognise Person", "Exit". Help me.. plzz

**Comment by AurangzaibKhan** [comment]
Sir i am having a problem in face recognition..... LBPH algorithm don't show the labels of unknown persons properly.... i.e: when it detect the unknown person it's label are matched with other whose added in database.... except showning them unknown..

**Comment by rragundez** [comment]
@AurangzaibKhan  this is probably because you are not setting any threshold. In one of the last notebooks I use the threshold implementation, take a look.
